apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: prometheus-datasource
spec:
  datasource:
    access: proxy
    editable: true
    secureJsonData: {}
    name: Prometheus
    url: 'http://prometheus-operated:9090'
    jsonData:
      timeInterval: 5s
    isDefault: true
    type: prometheus
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
