# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2022-latest"

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Developer"
MSSQL_AGENT_ENABLED:
    value: "true"
hostname: mssqllatest
containers:
  ports:
      containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroupChangePolicy: OnRootMismatch

containerSecurityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE

service:
  type: LoadBalancer
  port: 1433

pvc:
 StorageClass: "gp3-csi"
 userdbaccessMode: ReadWriteOnce
 userdbsize: 5Gi
 userlogaccessMode: ReadWriteOnce
 userlogsize: 5Gi
 tempdbaccessMode: ReadWriteOnce
 tempsize: 2Gi
 mssqldataaccessMode: ReadWriteOnce
 mssqldbsize: 2Gi
