apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mssql-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: mssql-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        sa_password: "{{ `{{ .mssql_password }}` }}"
  data:
  - secretKey: mssql_password
    remoteRef:
      key: "global/mssql"
      property: "secret"
